mode: CLIENT_SERVER
logging_level: DEBUG
production_mode: false
learning_materials: ./learning_assets
experiment_implementation: ./tests/model
experiment_results: ./tests/model/results
protocol: http # Either `http` or `https`
backend_address: 127.0.0.1
backend_port: 8000
frontend_address: 127.0.0.1
frontend_port: 3000
question_generation_model: t5
natural_language_inference_model: roberta
