name: Docker image

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t knowledge_verificator:latest .

      - name: Check disk usage
        run: |
          df -h
          docker system df

      - name: Save Docker image as an artifact
        run: |
          docker save knowledge_verificator:latest -o knowledge_verificator.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: knowledge_verificator
          path: knowledge_verificator.tar

permissions:
  contents: read
